### ISSUE TITLE
Vers. 1.10 very slow (eat CPU) on winforms with much string ressources 

### ISSUE THREAD

**Issue by devurmel** [mrlacey/StringResourceVisualizer#13]
### Installed product versions
- Visual Studio: 15.9.2
- This extension: StringResourceVisualizer 1.10

### Description
On vb.net winforms project with much ressources  after todays update to vers. 1.1
Eat CPU 

### Steps to recreate
After uninstall and installing previous version it's ok

### Current behavior
Slows down IDE

**Comment by mrlacey** [comment]
Before version 1.1 it did not support VB projects so that's why it wouldn't impact resources on a VB project previously.

Is the project this is having issues with public so I can test against it?
Was the same behavior expereinced with smaller projects too?
Can you quantify "much string resources"? Lots of files, multiple entries? - This will allow me to test against something similar to what you're having the problems on.

**Comment by mrlacey** [comment]
I created a .resx file with 10000 entries and it did have an impact on CPU usage.
I can imagine on a machine with few CPUs it might be a big issue.
WIll fix as a priority

**Comment by mrlacey** [comment]
Latest [CI build](http://vsixgallery.com/extension/StringResourceVisualizer.a05f89b1-98f8-4b37-8f84-4fdebc44aa25/) should be much kinder to your CPU.

**Comment by mrlacey** [comment]
[V1.2 is now in the marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.StringResourceVisualizer) and includes multiple changes to reduce unnecessary CPU use.
If using this new version still causes issues, please reopen this issue and provide more details about the solution as requested above.
