### ISSUE TITLE
Show language other than the default language

### ISSUE THREAD

**Issue by AbdullahUlber** [mrlacey/StringResourceVisualizer#28]
The ability to select a language other than the default language would be great.

**Comment by mrlacey** [comment]
Would a setting that allows the specifying of the language to use be enough?

I'm thinking that if the setting was specified as "de-DE" it would look for a version of the resource file that uses the German translations and return those resources if they exist. If that file doesn't exists or if that string isn't translated it would fall back to displaying the default resource value.


Do you **_need_** the ability to specify more than one language and it uses the order as a priority based on what's available? Or is support for a single language enough? 
_(I'm hoping a single language is enough as it will make things easier to implement. :wink: )_

**Comment by AbdullahUlber** [comment]
Your suggestion with selecting a single language and fallback to the default would be terrific. No need to select multiple languages. Many thanks for the super fast reply.

**Comment by mrlacey** [comment]
Early testing of this is looking positive. 😜 

![image](https://user-images.githubusercontent.com/189547/72460041-f82bec80-37c3-11ea-8c94-f4a535a43b46.png)

Note that in the above image, the German resource is used where a local resource exists (for Resource One), otherwise it falls back to using the default resource (For resource Two).

It knows to look for German because of a new setting:

![image](https://user-images.githubusercontent.com/189547/72460184-4214d280-37c4-11ea-94b2-ee0bcb451302.png)

There's no validation on the setting value provided but its use is not case sensitive. (Note the file name `MyRes.de-DE.resx` is mixed case but the setting is all lower case.)

Adding this also helped introduce a slight performance improvement too.

Hopefully shipping later this week after more testing.

**Comment by mrlacey** [comment]
[Version 1.5 is now available in the marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.StringResourceVisualizer) and includes this new functionality.

--- 

If this tool is useful to you, it helps other people know about it if you can [leave a review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.StringResourceVisualizer&ssr=false#review-details).

If you find lots of benefits from this and other tools I create, you can help support future development, feature requests, and bug fixes by [sponsoring my work](https://github.com/sponsors/mrlacey). Even small amounts help ;)
